GET http://127.0.0.1:3000/users

###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "id" : 101,
    "name" : "ravi",
    "age" : 19
}

###
PUT http://127.0.0.1:3000/users/100
Content-Type: application/json

{
    "name" : "ravi kumar",
    "age" : 20
}

###
DELETE http://localhost:3000/users/101

