POST http://localhost:3000/product-app/products
Content-Type: application/json

{
  "productName": "Phone",
  "price": 30000,
  "brand": "Samsung"
}

###
POSt http://localhost:3000/user-app/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "testing2@gmail.com",
  "password": "john@1234"
}


###
PUT http://localhost:3000/user-app/user-cart/userId/69818b7e887b6966429e7a89/productId/69806950e6605751bd9da178


### REad user by id
GET http://localhost:3000/user-app/users/69807162aea36c92236df654