POST http://localhost:3000/product-app/products
Content-Type: application/json

{
  "productName": "Phone",
  "price": 30000,
  "brand": "Samsung"
}

###
POSt http://localhost:3000/user-app/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "testing1@gmail.com",
  "password": "john@1234"
}


###
PUT http://localhost:3000/user-app/user-cart/userid/69807162aea36c92236df654/productid/69806c42abc5e470cff30296

