GET http://127.0.0.1:3000/users

###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "id" : 101,
    "name" : "ravi",
    "age" : 19
}

###
PUT http://127.0.0.1:3000/users/100
Content-Type: application/json

{
    "name" : "ravi kumar",
    "age" : 20
}

###
DELETE http://localhost:3000/users/101


###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/apple


###
POST http://localhost:3000/products
Content-Type: application/json

{
    "productId" : 201,
    "name" : "laptop",
    "price" : 5000,
    "brand" : "apple"
}

###
PUT http://localhost:3000/products/200
Content-Type: application/json

{
    "productId" : 200,
    "name" : "laptop",
    "price" : 55000,
    "brand" : "hp"
}

###
DELETE http://localhost:3000/products/200